name: Feature Request
description: Suggest an idea or new feature for this project
title: "[FEAT]: "
labels: ["feat"]
projects: ["vespaiach/1"]
body:
    - type: markdown
      attributes:
          value: Please fill out the details below.

    - type: textarea
      id: problem-statement
      attributes:
          label: Describe Your Feature Request
          description: A clear and concise description of the problem or use case that this feature request addresses.
          placeholder: Describe the problem or use case here...
      validations:
          required: true

    - type: textarea
      id: additional-information
      attributes:
          label: Additional Information
          description: Any additional information, context, or examples related to this feature request.
          placeholder: Provide any extra details here...
      validations:
          required: false

    - type: textarea
      id: expected-behavior
      attributes:
          label: Expected Behaviors
          description: A clear and concise description of what you expected to happen or how the feature should behave. Use checklists if there are multiple expected behaviors.
          placeholder: Describe the expected behavior here...
      validations:
          required: true
