import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "team-works",
  description: "Generated by project scaffolder",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
